title: Eduardo Ferreira da Silva # your name (or website title) here
logo: "/images/Foto_Trader_Energia_Livre_4_cmpc.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Solid experience in the electrical energy commercial area. 
  <br><br>
  Portfolio, Risk, Price Analysis and Customer Portfolio Management Projects.
  <br><br>
  <a href="https://www.linkedin.com/in/eduardo-ferreira-01a8441b//">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-Y4D49LZY8T # your Google Analytics tracking ID here
