title: Eduardo Ferreira # your name (or website title) here
logo: "/images/Foto_1280x640.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Sou um profissional com experiência sólida na área comercial de energia elétrica, atuando desde 
2009 na estruturação de processos de aquisição de clientes, geração de receita e captação de 
investimentos. Possuo conhecimentos em Power BI, Python e Data Science, aplicando essas 
ferramentas em estratégias de trading, back testing, previsão de preços e uso de algoritmos de 
Machine Learning em diversos setores. 
  <br><br>
  Capacidade comprovada de resolver problemas sob 
pressão, adaptável a situações diversas, habilidades de comunicação e resolução de conflitos. 
Tenho interesse em trabalhar na área de finanças, mercado financeiro, gestão de processos e 
tecnologia, especialmente no mercado livre de energia. 
  <br><br>
  <a href="https://www.linkedin.com/in/eduardo-ferreira-01a8441b//">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-Y4D49LZY8T # your Google Analytics tracking ID here
