title: Eduardo Ferreira # your name (or website title) here
logo: "/images/Foto_1280x640.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Possuo experiência sólida na área comercial de energia elétrica, na estruturação de processos de aquisição de clientes, geração de receita e captação de 
  investimentos. Conhecimentos em Power BI, Python e Data Science, aplicando essas 
  ferramentas em estratégias de trading, back testing, previsão de preços e uso de algoritmos de 
  Machine Learning em diversos setores. 
  <br><br>
  Capacidade comprovada de resolver problemas sob 
  pressão, adaptável a situações diversas, habilidades de comunicação e resolução de conflitos. 
  <br><br>
  <a href="https://www.linkedin.com/in/eduardo-ferreira-01a8441b//">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-Y4D49LZY8T # your Google Analytics tracking ID here
